# GATE SIMULATION
###                              data preprocessing
                                                 made by Yangsuseong

In [2]:
import os, glob, csv, codecs
import shutil
import re
import itertools
import math

## 파일 골라내기
    dat_dir 과 슬라이싱 범위는 상황에 따라 변경해야함

In [3]:
#dat_dir = input("Insert Directory : ")
dat_dir = r"C:\Users\BraveHong\Documents\gate_git1"

dat_file_list = glob.glob(dat_dir + '/*.txt')
dat_file_list.sort()
print(dat_file_list)
print(dat_file_list[0][-20:])

['C:\\Users\\BraveHong\\Documents\\gate_git1\\testCoincidences.txt']
testCoincidences.txt


## 파일 읽어들여서 x,y,z 축 값만 남기고 다 버릴거야
    9, 10, 11, 32,33,34 번째 정보
    인덱스로는 8,9,10  31,32,33
        dat_list 리스트에 저장(x1,y1,z1,x2,y2,z2)

In [4]:
# 리스트 청크 함수 (리스트, 원하는 길이)
# 이거 하고나면 차원이 하나가 더 생겨서 언패킹함수를 사용하여 차원축소를 해야함
def chunks(l, n):
    n = max(1, n)
    return (l[i:i+n] for i in range(0, len(l), n))

In [5]:
# 언패킹(차원 축소)을 위한 함수
def chain(*iterables):
    # chain('ABC', 'DEF') --> ['A', 'B', 'C', 'D', 'E', 'F']
    for it in iterables:
        for element in it:
            yield element


In [6]:
dat_list_all = []
dat_list_pre = []
dat_list = []
dat_list_xyz = []


#print("--------------" + dat_file_list[i]) + "----------------")
print(str(len(dat_file_list)) + "개의 파일을 변환합니다.")
for i in range(len(dat_file_list)):
    idx = 0
    print(str(i+1) + "번째 파일")
    txt_data = open(dat_file_list[i],'r')
    for j in txt_data:
        j = " ".join(j.split())
        j = j.split(" ")
        dat_list_all.append(j)
        #print(dat_list_all)

1개의 파일을 변환합니다.
1번째 파일


In [7]:
        
dat_len = len(dat_list_all) - 1
    
for i in range(len(dat_list_all) -1):
    #print(i)
    dat_list_pre.append(dat_list_all[i][8])
    dat_list_pre.append(dat_list_all[i][9])
    dat_list_pre.append(dat_list_all[i][10])
    dat_list_pre.append(dat_list_all[i][31])
    dat_list_pre.append(dat_list_all[i][32])
    dat_list_pre.append(dat_list_all[i][33])
        
dat_list.append(list(chunks(dat_list_pre, 3)))
dat_list = list(itertools.chain(*dat_list))
dat_list_xyz.append(list(chunks(dat_list,2)))
dat_list_xyz = list(itertools.chain(*dat_list_xyz))
    
print("Finish")
txt_data.close()

Finish


## 이제 x,y,z 값을 가지고 각 디텍터 번호에 대표 값으로 변경시켜주는 작업을 할거야
    
    <데이터가 저장된 리스트 정보>
    dat_list_xyz[ Coincidence Num, Single(0 or 1), xyz(0 or 1 or 2) ]
    
        ex) 첫번째 coincidence에서 싱글1의 z값을 보려고 한다.
               dat_list_xyz[0][0][2]
            
                    '-1.603e-03'


    필요한 자료 : 각 디텍터의 좌표 및 범위, 각 디텍터의 대표값
    54개의 큰 if문(x좌표)을 만들고 그 안에서 모든 경우의 수를 만들자

## 평균화 작업을 하기 전에 10의 제곱수(e+01 or e+02)들을 숫자로 바꾸는 작업을 진행해야한다.
    ex) -4.389e+02    -->    -43.89 

In [8]:
print(dat_list_xyz[0][0][0])
print(float(dat_list_xyz[0][0][0][:-4]))

-4.254e+02
-4.254


### 파이썬에서는 자료형 변경해주면 알아서 변경됨......

In [9]:
#print(dat_list_xyz[0][0][0][:-4])
for i in range(dat_len):
    for j in range(2):
        for k in range(3):
            if(str(dat_list_xyz[i][j][k][-4:]) == "e-06"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10**-6) * 0.1)
                #print("e-06 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e-05"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10**-5)* 0.1)
                #print("e-05 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e-04"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10**-4)* 0.1)
                #print("e-04 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e-03"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10**-3)* 0.1)
                #print("e-03 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e-02"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10**-2)* 0.1)
                #print("e-02 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e-01"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10**-1)* 0.1)
                #print("e-01 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e+00"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4])* 0.1)
                #print("e+00 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e+01"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10)* 0.1)
                #print("e+01 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e+02"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10**2)* 0.1)
                #print("e+02 complete")
            if(str(dat_list_xyz[i][j][k][-4:]) == "e+03"):
                dat_list_xyz[i][j][k] = str(float(dat_list_xyz[i][j][k][:-4]) * (10**3)* 0.1)
                #print("e+03 complete")
print("Complete")                

Complete


## 제대로 바뀌었는지 확인 한번 하고

In [10]:
float(dat_list_xyz[0][0][0])

-42.54

In [11]:
# x,y,z 값 확인용 함수
def print_xyz(x, y, z):
    print("x : " + x + ",    y : " + y +  ",    z : " + z)

In [12]:
print_xyz(dat_list_xyz[0][0][0], dat_list_xyz[0][0][1], dat_list_xyz[0][0][2])

x : -42.54,    y : -13.850000000000001,    z : -0.00016430000000000004


---

# 디텍터의 각 좌표들을 구하자

# Detector 번호(Crystal)에 맞는 중심(대표)값을 배열로 만들자
    지금은 3x3 디텍터 모델에 맞는 함수를 만들었다.
    크리스탈의 갯수를 받아서 배열을 생성하는 함수도 생각해보자
    
    <함수의 인자들>
        find_xyz_center(원점으로부터의 거리, 크리스탈의 x축 길이, 크리스탈의 y축 길이, 크리스탈의 z축 길이)

In [13]:
# 각 크리스탈의 중심값을 얻어내기위한 함수 (3x3)
# find_xyz_center(원점으로부터의 거리, 크리스탈의 x축 길이, 크리스탈의 y축 길이, 크리스탈의 z축 길이)
def YSS_find_xyz_center(r, x_len, y_len, z_len):
    
    crystal_1 = [r + (x_len/2), y_len, -z_len]
    crystal_2 = [r + (x_len/2), 0, -z_len]
    crystal_3 = [r + (x_len/2), -y_len, -z_len]
    crystal_4 = [r + (x_len/2), y_len, 0]
    crystal_5 = [r + (x_len/2), 0, 0]
    crystal_6 = [r + (x_len/2), -y_len, 0]
    crystal_7 = [r + (x_len/2), y_len, z_len]
    crystal_8 = [r + (x_len/2), 0, z_len]
    crystal_9 = [r + (x_len/2), -y_len, z_len]
    detector_1 = [crystal_1, crystal_2, crystal_3, crystal_4, crystal_5, crystal_6, crystal_7, crystal_8, crystal_9]
    detector_2 = []
    detector_3 = []
    detector_4 = []
    detector_5 = []
    detector_6 = []
    
    for i in range(len(detector_1)):
        detector_2.append([format((detector_1[i][0]*math.cos(60*math.pi/180)) - (detector_1[i][1]*math.sin(60*math.pi/180)),".3f"),\
                           format((detector_1[i][0]*math.sin(60*math.pi/180)) + (detector_1[i][1]*math.cos(60*math.pi/180)),".3f"),\
                           format(detector_1[i][2],".3f")])
        detector_3.append([format((detector_1[i][0]*math.cos(120*math.pi/180)) - (detector_1[i][1]*math.sin(120*math.pi/180)),".3f"),\
                           format((detector_1[i][0]*math.sin(120*math.pi/180)) + (detector_1[i][1]*math.cos(120*math.pi/180)),".3f"),\
                           format(detector_1[i][2],".3f")])
        detector_4.append([format((detector_1[i][0]*math.cos(180*math.pi/180)) - (detector_1[i][1]*math.sin(180*math.pi/180)),".3f"),\
                           format((detector_1[i][0]*math.sin(180*math.pi/180)) + (detector_1[i][1]*math.cos(180*math.pi/180)),".3f"),\
                           format(detector_1[i][2],".3f")])
        detector_5.append([format((detector_1[i][0]*math.cos(240*math.pi/180)) - (detector_1[i][1]*math.sin(240*math.pi/180)),".3f"),\
                           format((detector_1[i][0]*math.sin(240*math.pi/180)) + (detector_1[i][1]*math.cos(240*math.pi/180)),".3f"),\
                           format(detector_1[i][2],".3f")])
        detector_6.append([format((detector_1[i][0]*math.cos(300*math.pi/180)) - (detector_1[i][1]*math.sin(300*math.pi/180)),".3f"),\
                           format((detector_1[i][0]*math.sin(300*math.pi/180)) + (detector_1[i][1]*math.cos(300*math.pi/180)),".3f"),\
                           format(detector_1[i][2],".3f")])
        
        
    total_crystal_location = [detector_1, detector_2, detector_3, detector_4, detector_5, detector_6]
    #print(total_crystal_location)
    
    return total_crystal_location

In [14]:
# 함수 돌리기 (r길이, x_len, y_len, z_len)
crystal_location = YSS_find_xyz_center(44, 3, 11, 13) 

# 이제 Detector 번호(Crystal)의 중심값을 받아 각 모서리의 좌표를 얻어오는 함수를 만들자
    이 정보를 이용하여 x,y,z 축의 범위를 지정해줄것이다.
    
    crystal_location[0][0][0]  -->  1번 디텍터의 1번 디텍터의 x좌표

In [15]:
# 각 디텍터의 중심값을 받아와 크리스탈의 모서리의 좌표를 구하는 함수
def find_cristal_edge(x, y, z, x_len, y_len, z_len):
    x = float(x)
    y = float(y)
    z = float(z)
    x_len = float(x_len)
    y_len = float(y_len)
    z_len = float(z_len)
    edge_a1 = [x-(x_len/2), y+(y_len/2), z-(z_len/2)]
    edge_b1 = [x-(x_len/2), y+(y_len/2), z+(z_len/2)]
    edge_c1 = [x-(x_len/2), y-(y_len/2), z-(z_len/2)]
    edge_d1 = [x-(x_len/2), y-(y_len/2), z+(z_len/2)]
    edge_a2 = [x+(x_len/2), y+(y_len/2), z-(z_len/2)]
    edge_b2 = [x+(x_len/2), y+(y_len/2), z+(z_len/2)]
    edge_c2 = [x+(x_len/2), y-(y_len/2), z-(z_len/2)]
    edge_d2 = [x+(x_len/2), y-(y_len/2), z+(z_len/2)]
    
    
    crystal_edge = [edge_a1, edge_b1, edge_c1, edge_d1, edge_a2, edge_b2, edge_c2, edge_d2]
    #print(crystal_edge)
    return crystal_edge

## 엣지좌표구해서 회전까지 한번에 하려했는데... 순서때문에 좌표구하는 함수랑 회전변환 함수랑 따로 구현하자

In [16]:
def rotate_edge(x, y, z, angle):
    x = float(x)
    y = float(y)
    z = float(z)
    rotate_crystal_edge_1.append([(x*math.cos(angle*math.pi/180)) - (y*math.sin(angle*math.pi/180)),\
                               (x*math.sin(angle*math.pi/180)) + (y*math.cos(angle*math.pi/180)),\
                                z])

# 이제 실행하자
    크리스탈 센터값 계산 함수(1번 디텍터만 계산 후 회전변환)

In [17]:
origin_crystal_edge = []
for i in range(1):
    for j in range(len(crystal_location[i])):
        origin_crystal_edge.append(find_cristal_edge(crystal_location[i][j][0],\
                          crystal_location[i][j][1],\
                          crystal_location[i][j][2],\
                          3, 11, 13))  
    
print(origin_crystal_edge)

[[[44.0, 16.5, -19.5], [44.0, 16.5, -6.5], [44.0, 5.5, -19.5], [44.0, 5.5, -6.5], [47.0, 16.5, -19.5], [47.0, 16.5, -6.5], [47.0, 5.5, -19.5], [47.0, 5.5, -6.5]], [[44.0, 5.5, -19.5], [44.0, 5.5, -6.5], [44.0, -5.5, -19.5], [44.0, -5.5, -6.5], [47.0, 5.5, -19.5], [47.0, 5.5, -6.5], [47.0, -5.5, -19.5], [47.0, -5.5, -6.5]], [[44.0, -5.5, -19.5], [44.0, -5.5, -6.5], [44.0, -16.5, -19.5], [44.0, -16.5, -6.5], [47.0, -5.5, -19.5], [47.0, -5.5, -6.5], [47.0, -16.5, -19.5], [47.0, -16.5, -6.5]], [[44.0, 16.5, -6.5], [44.0, 16.5, 6.5], [44.0, 5.5, -6.5], [44.0, 5.5, 6.5], [47.0, 16.5, -6.5], [47.0, 16.5, 6.5], [47.0, 5.5, -6.5], [47.0, 5.5, 6.5]], [[44.0, 5.5, -6.5], [44.0, 5.5, 6.5], [44.0, -5.5, -6.5], [44.0, -5.5, 6.5], [47.0, 5.5, -6.5], [47.0, 5.5, 6.5], [47.0, -5.5, -6.5], [47.0, -5.5, 6.5]], [[44.0, -5.5, -6.5], [44.0, -5.5, 6.5], [44.0, -16.5, -6.5], [44.0, -16.5, 6.5], [47.0, -5.5, -6.5], [47.0, -5.5, 6.5], [47.0, -16.5, -6.5], [47.0, -16.5, 6.5]], [[44.0, 16.5, 6.5], [44.0, 16.5, 19

    각 모서리값 계산 함수

In [18]:
rotate_crystal_edge = []
rotate_crystal_edge_1 = []


for i in range(len(origin_crystal_edge)):
    for j in range(len(origin_crystal_edge[i])):
        rotate_edge(origin_crystal_edge[i][j][0],\
                    origin_crystal_edge[i][j][1],\
                    origin_crystal_edge[i][j][2],\
                    0)
    rotate_crystal_edge.append(rotate_crystal_edge_1)
    rotate_crystal_edge_1 = []

for i in range(len(origin_crystal_edge)):
    for j in range(len(origin_crystal_edge[i])):
        rotate_edge(origin_crystal_edge[i][j][0],\
                    origin_crystal_edge[i][j][1],\
                    origin_crystal_edge[i][j][2],\
                    60)
    rotate_crystal_edge.append(rotate_crystal_edge_1)
    rotate_crystal_edge_1 = []
        
for i in range(len(origin_crystal_edge)):
    for j in range(len(origin_crystal_edge[i])):
        rotate_edge(origin_crystal_edge[i][j][0],\
                    origin_crystal_edge[i][j][1],\
                    origin_crystal_edge[i][j][2],\
                    120)
    rotate_crystal_edge.append(rotate_crystal_edge_1)
    rotate_crystal_edge_1 = []
        
for i in range(len(origin_crystal_edge)):
    for j in range(len(origin_crystal_edge[i])):
        rotate_edge(origin_crystal_edge[i][j][0],\
                    origin_crystal_edge[i][j][1],\
                    origin_crystal_edge[i][j][2],\
                    180)
    rotate_crystal_edge.append(rotate_crystal_edge_1)
    rotate_crystal_edge_1 = []
        
for i in range(len(origin_crystal_edge)):
    for j in range(len(origin_crystal_edge[i])):
        rotate_edge(origin_crystal_edge[i][j][0],\
                    origin_crystal_edge[i][j][1],\
                    origin_crystal_edge[i][j][2],\
                    240)
    rotate_crystal_edge.append(rotate_crystal_edge_1)
    rotate_crystal_edge_1 = []
        
for i in range(len(origin_crystal_edge)):
    for j in range(len(origin_crystal_edge[i])):
        rotate_edge(origin_crystal_edge[i][j][0],\
                    origin_crystal_edge[i][j][1],\
                    origin_crystal_edge[i][j][2],\
                    300)
    rotate_crystal_edge.append(rotate_crystal_edge_1)
    rotate_crystal_edge_1 = []

crystal_location[디텍터 번호][크리스탈 번호][xyz 인덱스]


rotate_crystal_edge[ 크리스탈 번호 ][ 모서리번호(a1,b1,c1,d1,a2,b2,c2,d2) ][ xyz 인덱스 ]

In [19]:
rotate_crystal_edge[4]

[[44.0, 5.5, -6.5],
 [44.0, 5.5, 6.5],
 [44.0, -5.5, -6.5],
 [44.0, -5.5, 6.5],
 [47.0, 5.5, -6.5],
 [47.0, 5.5, 6.5],
 [47.0, -5.5, -6.5],
 [47.0, -5.5, 6.5]]

In [20]:
print(crystal_location[0])
print("\n")
print(origin_crystal_edge)
print("\n")
print(rotate_crystal_edge[0][0])
len(rotate_crystal_edge)

[[45.5, 11, -13], [45.5, 0, -13], [45.5, -11, -13], [45.5, 11, 0], [45.5, 0, 0], [45.5, -11, 0], [45.5, 11, 13], [45.5, 0, 13], [45.5, -11, 13]]


[[[44.0, 16.5, -19.5], [44.0, 16.5, -6.5], [44.0, 5.5, -19.5], [44.0, 5.5, -6.5], [47.0, 16.5, -19.5], [47.0, 16.5, -6.5], [47.0, 5.5, -19.5], [47.0, 5.5, -6.5]], [[44.0, 5.5, -19.5], [44.0, 5.5, -6.5], [44.0, -5.5, -19.5], [44.0, -5.5, -6.5], [47.0, 5.5, -19.5], [47.0, 5.5, -6.5], [47.0, -5.5, -19.5], [47.0, -5.5, -6.5]], [[44.0, -5.5, -19.5], [44.0, -5.5, -6.5], [44.0, -16.5, -19.5], [44.0, -16.5, -6.5], [47.0, -5.5, -19.5], [47.0, -5.5, -6.5], [47.0, -16.5, -19.5], [47.0, -16.5, -6.5]], [[44.0, 16.5, -6.5], [44.0, 16.5, 6.5], [44.0, 5.5, -6.5], [44.0, 5.5, 6.5], [47.0, 16.5, -6.5], [47.0, 16.5, 6.5], [47.0, 5.5, -6.5], [47.0, 5.5, 6.5]], [[44.0, 5.5, -6.5], [44.0, 5.5, 6.5], [44.0, -5.5, -6.5], [44.0, -5.5, 6.5], [47.0, 5.5, -6.5], [47.0, 5.5, 6.5], [47.0, -5.5, -6.5], [47.0, -5.5, 6.5]], [[44.0, -5.5, -6.5], [44.0, -5.5, 6.5], [44.0, -16

54

---

## 이제 대표값으로 바꾸자
--- 
2019.01.28
여기부터 생각해보자.

디텍터번호 0,1,5 번 범위와 2,3,4번 범위가 반대인것을 활용해보자

일단 모서리좌표를 디텍터별로 나눠야할거같아

In [21]:
# 모서리 좌표 리스트를 차원을 늘려서 디텍터별로 나누자
rotate_crystal_edge_chunks = []
rotate_crystal_edge_chunks.append(list(chunks(rotate_crystal_edge, 9)))
rotate_crystal_edge_chunks = list(itertools.chain(*rotate_crystal_edge_chunks))

   rotate_crystal_edge_chunks[디텍터 번호][크리스탈 번호][모서리 위치][xyz 좌표(0,1,2)]

In [22]:
rotate_crystal_edge_chunks[0][0][4][0]

47.0

In [23]:
# 중심값 =  crystal_location[디텍터 번호][크리스탈 번호][xyz]
len(crystal_location[0])
len(rotate_crystal_edge_chunks[0])

9

In [24]:
# 모든 좌표값을 평균값으로 변환하는 함수
def normalization(x, y, z):
    x = float(x)
    y = float(y)
    z = float(z)
    
    
    for i in range(len(rotate_crystal_edge_chunks)):
        for j in range(len(rotate_crystal_edge_chunks[i])):
            if(i==0):
                if(x>=rotate_crystal_edge_chunks[0][j][0][0] and x<rotate_crystal_edge_chunks[0][j][4][0]):
                    if(y>=rotate_crystal_edge_chunks[0][j][2][1] and y<rotate_crystal_edge_chunks[0][j][0][1]):
                        if(z>=rotate_crystal_edge_chunks[0][j][0][2] and z<rotate_crystal_edge_chunks[0][j][1][2]):
                            ave_xyz_list.append(crystal_location[0][j])
            if(i==1):
                if(x>=rotate_crystal_edge_chunks[1][j][1][0] and x<rotate_crystal_edge_chunks[1][j][3][0]):
                    if(y>=rotate_crystal_edge_chunks[1][j][3][1] and y<rotate_crystal_edge_chunks[1][j][5][1]):
                        if(z>=rotate_crystal_edge_chunks[1][j][0][2] and z<rotate_crystal_edge_chunks[1][j][1][2]):
                            ave_xyz_list.append(crystal_location[1][j])
            if(i==2):
                if(x>=rotate_crystal_edge_chunks[2][j][1][0] and x<rotate_crystal_edge_chunks[2][j][3][0]):
                    if(y>=rotate_crystal_edge_chunks[2][j][1][1] and y<rotate_crystal_edge_chunks[2][j][7][1]):
                        if(z>=rotate_crystal_edge_chunks[2][j][0][2] and z<rotate_crystal_edge_chunks[2][j][1][2]):
                            ave_xyz_list.append(crystal_location[2][j])
            if(i==3):
                if(x<rotate_crystal_edge_chunks[3][j][1][0] and x>=rotate_crystal_edge_chunks[3][j][3][0]):
                    if(y<rotate_crystal_edge_chunks[3][j][2][1] and y>=rotate_crystal_edge_chunks[3][j][0][1]):
                        if(z>=rotate_crystal_edge_chunks[3][j][0][2] and z<rotate_crystal_edge_chunks[3][j][1][2]):
                            ave_xyz_list.append(crystal_location[3][j])
            if(i==4):
                if(x<rotate_crystal_edge_chunks[4][j][1][0] and x>=rotate_crystal_edge_chunks[4][j][3][0]):
                    if(y<rotate_crystal_edge_chunks[4][j][3][1] and y>=rotate_crystal_edge_chunks[4][j][5][1]):
                        if(z>=rotate_crystal_edge_chunks[4][j][0][2] and z<rotate_crystal_edge_chunks[4][j][1][2]):
                            ave_xyz_list.append(crystal_location[4][j])
            if(i==5):
                if(x<rotate_crystal_edge_chunks[5][j][1][0] and x>=rotate_crystal_edge_chunks[5][j][3][0]):
                    if(y<rotate_crystal_edge_chunks[5][j][1][1] and y>=rotate_crystal_edge_chunks[5][j][7][1]):
                        if(z>=rotate_crystal_edge_chunks[5][j][0][2] and z<rotate_crystal_edge_chunks[5][j][1][2]):
                            ave_xyz_list.append(crystal_location[5][j])

        
      

In [25]:
ave_xyz_list = []
for i in range(len(dat_list_xyz)):
    for j in range(2):
        normalization(dat_list_xyz[i][j][0], dat_list_xyz[i][j][1], dat_list_xyz[i][j][2])
    
        # 이제 각 정보들을 비교할 데이터를 가져와서 비교해서 바꿔주는 작업을 하자
        # 바꾸는 작업은 위에 함수를 포문으로 계속 불러와야해
        #print(dat_list_xyz[i][j][k])


In [26]:
print(dat_list_xyz[0][0][0] + ", " + dat_list_xyz[0][0][1] + ", " + dat_list_xyz[0][0][2])

-42.54, -13.850000000000001, -0.00016430000000000004


In [27]:
dat_list_xyz[0][0]

['-42.54', '-13.850000000000001', '-0.00016430000000000004']

소수점 x자리까지 자르는거 하고 single 별로 다시 묶자

In [28]:
ave_xyz_final = []
ave_xyz_final.append(list(chunks(ave_xyz_list, 2)))
ave_xyz_final = list(itertools.chain(*ave_xyz_final))
print(ave_xyz_final, end = ",")

[[['-13.224', '-44.904', '0.000'], ['32.276', '33.904', '0.000']], [['-32.276', '-33.904', '0.000'], [45.5, 0, 0]], [[45.5, 11, 0], ['32.276', '33.904', '0.000']], [['-13.224', '-44.904', '0.000'], ['22.750', '39.404', '0.000']], [['13.224', '44.904', '0.000'], ['-13.224', '-44.904', '0.000']], [['32.276', '33.904', '0.000'], ['-32.276', '-33.904', '0.000']], [['-13.224', '44.904', '0.000'], ['13.224', '-44.904', '0.000']], [['-13.224', '44.904', '0.000'], ['13.224', '-44.904', '0.000']], [['-13.224', '44.904', '0.000'], [45.5, -11, 0]], [['32.276', '33.904', '0.000'], ['-32.276', '-33.904', '0.000']], [['-13.224', '44.904', '0.000'], ['-22.750', '39.404', '0.000']], [[45.5, -11, 0], ['-13.224', '44.904', '0.000']], [['-13.224', '44.904', '0.000'], ['22.750', '-39.404', '-13.000']], [[45.5, 11, 0], [45.5, 11, 0]], [['32.276', '33.904', '0.000'], ['13.224', '44.904', '0.000']], [['-13.224', '-44.904', '0.000'], [45.5, 11, 0]], [['32.276', '-33.904', '0.000'], ['-32.276', '33.904', '0.00

In [29]:
ave_xyz_final

[[['-13.224', '-44.904', '0.000'], ['32.276', '33.904', '0.000']],
 [['-32.276', '-33.904', '0.000'], [45.5, 0, 0]],
 [[45.5, 11, 0], ['32.276', '33.904', '0.000']],
 [['-13.224', '-44.904', '0.000'], ['22.750', '39.404', '0.000']],
 [['13.224', '44.904', '0.000'], ['-13.224', '-44.904', '0.000']],
 [['32.276', '33.904', '0.000'], ['-32.276', '-33.904', '0.000']],
 [['-13.224', '44.904', '0.000'], ['13.224', '-44.904', '0.000']],
 [['-13.224', '44.904', '0.000'], ['13.224', '-44.904', '0.000']],
 [['-13.224', '44.904', '0.000'], [45.5, -11, 0]],
 [['32.276', '33.904', '0.000'], ['-32.276', '-33.904', '0.000']],
 [['-13.224', '44.904', '0.000'], ['-22.750', '39.404', '0.000']],
 [[45.5, -11, 0], ['-13.224', '44.904', '0.000']],
 [['-13.224', '44.904', '0.000'], ['22.750', '-39.404', '-13.000']],
 [[45.5, 11, 0], [45.5, 11, 0]],
 [['32.276', '33.904', '0.000'], ['13.224', '44.904', '0.000']],
 [['-13.224', '-44.904', '0.000'], [45.5, 11, 0]],
 [['32.276', '-33.904', '0.000'], ['-32.276',

---


In [277]:
b=np.array(ave_xyz_final)
b.shape

(882,)

---

In [34]:
import math
import numpy as np



In [76]:
def cal_angle (det1,det2):
    
    det_x1 = det1[0]
    det_y1 = det1[1]
    det_z1 = det1[2]
    det_x2 = det2[0]
    det_y2 = det2[1]
    det_z2 = det2[2]
    det_x1 = float(det_x1)
    det_y1 = float(det_y1)
    det_z1 = float(det_z1)
    det_x2 = float(det_x2)
    det_y2 = float(det_y2)
    det_z2 = float(det_z2)
    a = np.abs(det_x1 - det_x2)
    b = np.abs(det_y1 - det_y2)
    d = 91 #  두 디텍터 간의 직선 거리 
    theta = math.atan( np.abs( det_z1 - det_z2 ) / d)
    
    if b == 0 :
        phi = 90
        radius = det_y1
    else:
        phi = math.atan(- a / b)
        
        if a == 0:
            phi = 0
            radius = det_x1
        else:
            radius = np.abs( -( b / a ) * det_x1 * np.sin(phi) + det_y1 * np.sin(phi))
    
    result = [radius, phi, theta]
    

    return  result


In [231]:
a=np.array(ave_xyz_final)

In [79]:
record = []
for i in range(0,len(a)-1):
    record.append(cal_angle(a[i][0],a[i][1]))
        

In [69]:
record

[[10.999757996673752, -0.5236004884846109, 0],
 [18.181876157061872, -1.159714049065764, 0],
 [33.90376541758742, -0.5236108727833061, 0],
 [5.46012693269337, -0.4033074374378385, 0],
 [0.0, -0.28639864383287295, 0],
 [0.0, -0.7608035467411005, 0],
 [25.370706178884298, -0.28639864383287295, 0],
 [25.370706178884298, -0.28639864383287295, 0],
 [41.64120139869551, -0.8099945211381164, 0],
 [0.0, -0.7608035467411005, 0],
 [45.49986500804138, -1.0471848490249271, 0],
 [39.339476618709455, -0.8099945211381164, 0],
 [29.78615051382382, -0.4033074374378385, 0.1418970546041639],
 [11.0, 90, 0],
 [13.223154912608159, -1.0471848490249274, 0],
 [23.405241891472507, -0.8099945211381164, 0],
 [46.7538643297267, -0.7608035467411005, 0],
 [25.370706178884298, -0.28639864383287295, 0],
 [46.7538643297267, -0.7608035467411005, 0],
 [21.383564686916976, -0.7608035467411004, 0.1418970546041639],
 [0.0, -0.28639864383287295, 0],
 [40.53911557921289, -1.3335895279112526, 0],
 [39.33911692910623, -0.237201

In [83]:
record[12]

[29.78615051382382, -0.4033074374378385, 0.1418970546041639]

In [81]:
ave_xyz_final[12]

[['-13.224', '44.904', '0.000'], ['22.750', '-39.404', '-13.000']]

# 변경한 값중에서 theta 값이 0인 것들만 남길거야. 그러면 이제 2D 데이터가 되겠지?

In [305]:
b=np.array(record)
b

array([[ 10.999758  ,  -0.52360049,   0.        ],
       [ 18.18187616,  -1.15971405,   0.        ],
       [ 33.90376542,  -0.52361087,   0.        ],
       ...,
       [ 44.904     ,  90.        ,   0.        ],
       [ 25.37070618,  -0.28639864,   0.        ],
       [-44.904     ,  90.        ,   0.        ]])

In [307]:
b[:][1][:]

array([18.18187616, -1.15971405,  0.        ])

In [310]:

c=[]

for i in range(0,len(b)):

    print(b[:][i][2])
    if (b[:][i][2]== 0):
        c.append((b[:][i][:]))
    

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.1418970546041639
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.1418970546041639
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.1418970546041639
0.1418970546041639
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.27829965900511133
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0.0
0.0
0.0
0.0
0.1418970546041639
0.0
0

In [315]:
c

[array([10.999758  , -0.52360049,  0.        ]),
 array([18.18187616, -1.15971405,  0.        ]),
 array([33.90376542, -0.52361087,  0.        ]),
 array([ 5.46012693, -0.40330744,  0.        ]),
 array([ 0.        , -0.28639864,  0.        ]),
 array([ 0.        , -0.76080355,  0.        ]),
 array([25.37070618, -0.28639864,  0.        ]),
 array([25.37070618, -0.28639864,  0.        ]),
 array([41.6412014 , -0.80999452,  0.        ]),
 array([ 0.        , -0.76080355,  0.        ]),
 array([45.49986501, -1.04718485,  0.        ]),
 array([39.33947662, -0.80999452,  0.        ]),
 array([11., 90.,  0.]),
 array([13.22315491, -1.04718485,  0.        ]),
 array([23.40524189, -0.80999452,  0.        ]),
 array([46.75386433, -0.76080355,  0.        ]),
 array([25.37070618, -0.28639864,  0.        ]),
 array([46.75386433, -0.76080355,  0.        ]),
 array([ 0.        , -0.28639864,  0.        ]),
 array([40.53911558, -1.33358953,  0.        ]),
 array([39.33911693, -0.237201  ,  0.       

In [264]:
b.shape

(881, 3)

In [265]:
b.ndim

2

In [266]:
b.dtype

dtype('float64')

In [267]:
type(b)

numpy.ndarray

In [268]:
c = np.any(b == 0)
type(c)

numpy.bool_

NameError: name 'brg' is not defined

## 2D 데이터를 이용하여 Sinogram 만들어내자
    (R, Phi) += 1